import{useEffect,useState}from'react';import{catalog}from'./data';import{getAllDays,getDay,importDays,RecordDay,saveDay,Severity,VitalReading,FluidTally,LifeEvent}from'./db';
const iso=()=>new Date().toLocaleDateString('en-CA');
const ev=():VitalReading=>({time:'',bp:'',heartRate:'',temperature:'',context:''});
const tally=():FluidTally=>({water32:0,drink12:0,small:0,medium:0,large:0,veryLarge:0});
const blank=(date=iso()):RecordDay=>({date,status:'Typical',burden:0,energy:0,upright:0,sleep:0,symptoms:{},measurements:{fluidUnit:'oz',tempUnit:'°F',electrolyte:false,vitals:[ev(),ev(),ev()],tally:tally()},activity:{physical:'None',cognitive:'None',social:'None',delayed:'None'},cycle:{resetDate:'',pmdd:'None',note:''},lifeEvents:[],notes:'',updatedAt:new Date().toISOString()});
const labels=['None','Mild','Moderate','Severe'];
const defaults=['Brain fog','Dizziness','Lightheadedness','Post-exertional malaise','Delayed crashes','Energy collapse','Nausea','Weakness','Non-restorative sleep','Sensory overload','Headache','Temperature dysregulation'];
function normalize(v:any):RecordDay{const b=blank(v.date||iso()),m=v.measurements||{},vs=Array.isArray(m.vitals)?m.vitals.slice(0,3):[];while(vs.length<3)vs.push(ev());if(!vs.some((x:VitalReading)=>x.bp||x.heartRate||x.temperature)&&(m.bp||m.heartRate||m.temperature))vs[0]={time:'',bp:m.bp||'',heartRate:m.heartRate||'',temperature:m.temperature||'',context:''};const oldFluid=Number(m.fluid)||0,oldUrine=Number(m.urine)||0;const t={...tally(),...(m.tally||{})};if(!m.tally&&oldFluid)t.water32=Math.round(oldFluid/32);if(!m.tally&&oldUrine)t.medium=Math.max(1,Math.round((m.fluidUnit==='mL'?oldUrine:oldUrine*29.5735)/275));return{...b,...v,symptoms:v.symptoms||{},measurements:{...b.measurements,...m,vitals:vs,tally:t},activity:{...b.activity,...v.activity},cycle:{...b.cycle,...v.cycle},lifeEvents:Array.isArray(v.lifeEvents)?v.lifeEvents:[]}}
const intakeMl=(t:FluidTally)=>(t.water32*32+t.drink12*12)*29.5735;
const outputMl=(t:FluidTally)=>t.small*150+t.medium*275+t.large*425+t.veryLarge*600;
const cycleInfo=(date:string,reset:string)=>{if(!reset)return{day:0,phase:'Not estimated'};const day=Math.floor((new Date(date+'T12:00:00').getTime()-new Date(reset+'T12:00:00').getTime())/86400000)+1;if(day<1)return{day,phase:'Before anchor'};const normalized=((day-1)%28)+1;return{day,phase:normalized<=5?'Estimated menstrual':normalized<=13?'Estimated follicular':normalized<=16?'Estimated ovulatory':'Estimated luteal'}};
function Score({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <label className="score"><span>{label}</span><input type="range" min="0" max="5" value={value} onChange={e=>set(+e.target.value)}/><b>{value}</b></label>}
function Counter({label,sub,value,set}:{label:string;sub?:string;value:number;set:(n:number)=>void}){return <div className="counter"><div><strong>{label}</strong>{sub&&<small>{sub}</small>}</div><div className="counterButtons"><button onClick={()=>set(Math.max(0,value-1))}>−</button><b>{value}</b><button onClick={()=>set(value+1)}>+</button></div></div>}
function download(s:string,n:string,t:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:t}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
function avg(a:number[]){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function flags(days:RecordDay[]){const r=days.slice(-3),b=days.slice(-17,-3);if(r.length<2||b.length<7)return[];const out:string[]=[];const cmp=(name:string,rv:number[],bv:number[],dir:'up'|'down')=>{if(rv.length<2||bv.length<7)return;const x=avg(rv),y=avg(bv);if((dir==='up'&&x-y>=1)||(dir==='down'&&x-y<=-1))out.push(`${name}: ${x.toFixed(1)} recently vs ${y.toFixed(1)} baseline`)};const s=(ds:RecordDay[],n:string)=>ds.flatMap(d=>d.symptoms[n]?[d.symptoms[n].severity]:[]);cmp('Fatigue after standing above baseline',s(r,'Fatigue after standing'),s(b,'Fatigue after standing'),'up');cmp('Lightheadedness above baseline',s(r,'Lightheadedness'),s(b,'Lightheadedness'),'up');cmp('Energy below baseline',r.map(d=>d.energy),b.map(d=>d.energy),'down');cmp('Upright tolerance below baseline',r.map(d=>d.upright),b.map(d=>d.upright),'down');cmp('Overall burden above baseline',r.map(d=>d.burden),b.map(d=>d.burden),'up');return out}
function aiText(days:RecordDay[]){const x=['# Autonomic Tracker Export','','Missing values mean not recorded. Estimates are approximate and user-entered.'];for(const d of days){const i=intakeMl(d.measurements.tally),o=outputMl(d.measurements.tally),c=cycleInfo(d.date,d.cycle.resetDate);x.push('',`## ${d.date}`,`Status: ${d.status}; burden ${d.burden}/5; energy ${d.energy}/5; upright ${d.upright}/5; sleep ${d.sleep}/5`,`Estimated intake: ${Math.round(i)} mL; estimated urine output: ${Math.round(o)} mL; ratio: ${i?Math.round(o/i*100)+'%':'not available'}`,`Tallies: 32oz water ${d.measurements.tally.water32}; 12oz drinks ${d.measurements.tally.drink12}; voids small ${d.measurements.tally.small}, medium ${d.measurements.tally.medium}, large ${d.measurements.tally.large}, very large ${d.measurements.tally.veryLarge}`,`Electrolyte packet: ${d.measurements.electrolyte?'Yes':'No'}`,`Cycle estimate: day ${c.day||'unknown'}, ${c.phase}; PMDD ${d.cycle.pmdd}`);d.measurements.vitals.filter(v=>v.time||v.bp||v.heartRate||v.temperature||v.context).forEach(v=>x.push(`Vital: ${v.time||'?'}; BP ${v.bp||'?'}; HR ${v.heartRate||'?'}; temp ${v.temperature||'?'}${d.measurements.tempUnit}; ${v.context||'no context'}`));Object.entries(d.symptoms).filter(([,v])=>v.severity>0).forEach(([n,v])=>x.push(`Symptom: ${n} = ${labels[v.severity]}${v.note?' | '+v.note:''}`));d.lifeEvents.forEach(e=>x.push(`Life event: ${e.title}${e.note?' | '+e.note:''}`));if(d.notes)x.push(`Notes: ${d.notes}`)}x.push('','Please identify direct patterns, possible relationships requiring confirmation, missing-data limitations, and questions for a healthcare professional. Do not diagnose or recommend treatment changes.');return x.join('\n')}
export default function App(){const[tab,setTab]=useState('Today'),[date,setDate]=useState(iso()),[day,setDay]=useState<RecordDay>(blank()),[days,setDays]=useState<RecordDay[]>([]),[saved,setSaved]=useState(''),[faves,setFaves]=useState<string[]>(()=>JSON.parse(localStorage.getItem('favorites')||JSON.stringify(defaults))),[open,setOpen]=useState<string[]>([]),[eventTitle,setEventTitle]=useState(''),[eventNote,setEventNote]=useState('');const load=async()=>setDays((await getAllDays()).map(normalize));useEffect(()=>{getDay(date).then(v=>setDay(v?normalize(v):blank(date)));load()},[date]);useEffect(()=>{const t=setTimeout(()=>saveDay({...day,updatedAt:new Date().toISOString()}).then(()=>{setSaved('Saved');load()}).catch(()=>setSaved('Save failed')),500);return()=>clearTimeout(t)},[day]);const patch=(p:Partial<RecordDay>)=>setDay(d=>({...d,...p}));const setT=(k:keyof FluidTally,n:number)=>setDay(d=>({...d,measurements:{...d.measurements,tally:{...d.measurements.tally,[k]:n}}}));const setV=(i:number,k:keyof VitalReading,v:string)=>setDay(d=>({...d,measurements:{...d.measurements,vitals:d.measurements.vitals.map((x,j)=>j===i?{...x,[k]:v}:x)}}));const sev=(n:string)=>day.symptoms[n]?.severity||0;const sym=(n:string)=><div className="sym" key={n}><div className="sym-title"><button className={'star '+(faves.includes(n)?'on':'')} onClick={()=>{const q=faves.includes(n)?faves.filter(x=>x!==n):faves.length<12?[...faves,n]:faves;setFaves(q);localStorage.setItem('favorites',JSON.stringify(q))}}>★</button><span>{n}</span></div><div className="severity">{labels.map((x,i)=><button key={x} className={sev(n)===i?'selected':''} onClick={()=>setDay(d=>({...d,symptoms:{...d.symptoms,[n]:{severity:i as Severity,note:d.symptoms[n]?.note||''}}}))}>{x}</button>)}</div>{sev(n)>0&&<input className="note" placeholder="Optional note" value={day.symptoms[n]?.note||''} onChange={e=>setDay(d=>({...d,symptoms:{...d.symptoms,[n]:{severity:sev(n),note:e.target.value}}}))}/>}</div>;const iMl=intakeMl(day.measurements.tally),oMl=outputMl(day.measurements.tally),ratio=iMl?oMl/iMl*100:0,ci=cycleInfo(day.date,day.cycle.resetDate),trend=flags(days);
return <div className="app"><header><div><h1>Autonomic Daily</h1><small>Private, local-first symptom log</small></div><span>{saved}</span></header><main>
{tab==='Today'&&<><section className="card date"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></section>
<section className="card fluidHero"><h2>Quick fluid tally</h2><h3>Intake</h3><Counter label="32 oz water bottle" value={day.measurements.tally.water32} set={n=>setT('water32',n)}/><Counter label="12 oz beverage" value={day.measurements.tally.drink12} set={n=>setT('drink12',n)}/><h3>Urine output</h3><Counter label="Small" sub="Estimated 100–200 mL" value={day.measurements.tally.small} set={n=>setT('small',n)}/><Counter label="Medium" sub="Estimated 200–350 mL" value={day.measurements.tally.medium} set={n=>setT('medium',n)}/><Counter label="Large" sub="Estimated 350–500 mL" value={day.measurements.tally.large} set={n=>setT('large',n)}/><Counter label="Very large" sub="Estimated 500–700+ mL" value={day.measurements.tally.veryLarge} set={n=>setT('veryLarge',n)}/><label className="check"><input type="checkbox" checked={day.measurements.electrolyte} onChange={e=>setDay(d=>({...d,measurements:{...d.measurements,electrolyte:e.target.checked}}))}/><span>Used one electrolyte packet today</span></label><div className={'throughput '+(!iMl?'neutral':ratio<60||ratio>80?'outside':'inside')}><strong>Estimated throughput</strong><b>{iMl?Math.round(ratio)+'%':'Add intake to calculate'}</b><span>{!iMl?'No ratio yet':ratio>=60&&ratio<=80?'Within your 60–80% tracking band':'Outside your 60–80% tracking band'}</span><small>{Math.round(iMl)} mL estimated intake · {Math.round(oMl)} mL estimated urine output</small></div><p className="disclaimer">Approximate tracking only. Beverage sizes and void categories are estimates, and this ratio excludes food fluid, sweat, breathing, stool, and other losses.</p></section>
<section className="card"><h2>Quick check-in</h2><div className="status">{['Better than usual','Typical','Worse than usual','Flare / Crash'].map(x=><button key={x} className={day.status===x?'selected':''} onClick={()=>patch({status:x})}>{x}</button>)}</div><Score label="Overall symptom burden" value={day.burden} set={n=>patch({burden:n})}/><Score label="Available energy" value={day.energy} set={n=>patch({energy:n})}/><Score label="Upright tolerance" value={day.upright} set={n=>patch({upright:n})}/><Score label="Sleep quality" value={day.sleep} set={n=>patch({sleep:n})}/></section>
<section className="card"><h2>Pinned symptoms</h2>{faves.filter(n=>Object.values(catalog).flat().includes(n)).map(sym)}</section>
<section className="card"><h2>Vital readings</h2><p className="hint">Three optional readings.</p>{day.measurements.vitals.map((v,j)=><div className="vital" key={j}><h3>Reading {j+1}</h3><div className="grid"><label>Time<input type="time" value={v.time} onChange={e=>setV(j,'time',e.target.value)}/></label><label>Blood pressure<input value={v.bp} onChange={e=>setV(j,'bp',e.target.value)}/></label><label>Heart rate<input inputMode="numeric" value={v.heartRate} onChange={e=>setV(j,'heartRate',e.target.value)}/></label><label>Temperature<input inputMode="decimal" value={v.temperature} onChange={e=>setV(j,'temperature',e.target.value)}/></label><label>Context<select value={v.context} onChange={e=>setV(j,'context',e.target.value)}><option value="">Not recorded</option><option>Resting</option><option>Upright</option><option>After activity</option><option>Symptomatic</option><option>Other</option></select></label></div></div>)}</section>
<section className="card"><h2>All symptoms</h2>{Object.entries(catalog).map(([c,l])=><div className="category" key={c}><button className="category-head" onClick={()=>setOpen(o=>o.includes(c)?o.filter(x=>x!==c):[...o,c])}>{c}<span>{open.includes(c)?'−':'+'}</span></button>{open.includes(c)&&l.map(sym)}</div>)}</section>
<section className="card"><h2>Life events</h2><p className="hint">Examples: antibiotic recovery, infection, travel, medication change, injury, or major stress.</p><label>Event<input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Antibiotic recovery"/></label><label>Optional note<input value={eventNote} onChange={e=>setEventNote(e.target.value)}/></label><button className="primary" disabled={!eventTitle.trim()} onClick={()=>{const e:LifeEvent={id:crypto.randomUUID(),date:day.date,title:eventTitle.trim(),note:eventNote.trim()};setDay(d=>({...d,lifeEvents:[...d.lifeEvents,e]}));setEventTitle('');setEventNote('')}}>Add event</button>{day.lifeEvents.map(e=><div className="event" key={e.id}><div><strong>{e.title}</strong>{e.note&&<small>{e.note}</small>}</div><button onClick={()=>setDay(d=>({...d,lifeEvents:d.lifeEvents.filter(x=>x.id!==e.id)}))}>Remove</button></div>)}</section>
<section className="card"><h2>Cycle estimate</h2><div className="cycleSummary"><b>{ci.day>0?`Estimated cycle day ${ci.day}`:'No cycle anchor yet'}</b><span>{ci.phase}</span></div><button className="primary" onClick={()=>setDay(d=>({...d,cycle:{...d.cycle,resetDate:d.date}}))}>PMDD symptoms started today / reset estimate</button><label>PMDD severity<select value={day.cycle.pmdd} onChange={e=>setDay(d=>({...d,cycle:{...d.cycle,pmdd:e.target.value}}))}>{labels.map(x=><option key={x}>{x}</option>)}</select></label><textarea placeholder="Cycle notes" value={day.cycle.note} onChange={e=>setDay(d=>({...d,cycle:{...d.cycle,note:e.target.value}}))}/><p className="disclaimer">Phase is a rough 28-day estimate from your most recent reset marker. Cycles vary, and this is not an ovulation or fertility prediction.</p></section>
<section className="card"><h2>Activity and delayed effects</h2>{(['physical','cognitive','social']as const).map(k=><label key={k}>{k==='social'?'Social / sensory':k[0].toUpperCase()+k.slice(1)} exertion<select value={day.activity[k]} onChange={e=>setDay(d=>({...d,activity:{...d.activity,[k]:e.target.value}}))}>{['None','Light','Moderate','High'].map(x=><option key={x}>{x}</option>)}</select></label>)}<label>Delayed worsening<select value={day.activity.delayed} onChange={e=>setDay(d=>({...d,activity:{...d.activity,delayed:e.target.value}}))}>{['None','Same day','Next day','Two to three days later'].map(x=><option key={x}>{x}</option>)}</select></label></section><section className="card"><h2>Daily notes</h2><textarea value={day.notes} onChange={e=>patch({notes:e.target.value})}/></section></>}
{tab==='History'&&<section className="card"><h2>History</h2>{days.slice().reverse().map(d=><button key={d.date} className="history" onClick={()=>{setDate(d.date);setTab('Today')}}><b>{d.date}</b><span>{d.status} · burden {d.burden}/5</span></button>)}</section>}
{tab==='Trends'&&<><section className="card"><h2>Changes from recent baseline</h2>{trend.length?trend.map(x=><div className="flag" key={x}>{x}</div>):<p>No notable changes detected, or not enough data yet.</p>}<p className="disclaimer">Observational only. These flags cannot identify a cause or diagnose illness.</p></section></>}
{tab==='Export'&&<section className="card"><h2>Export and backup</h2><button className="primary" onClick={()=>download(aiText(days),`autonomic-tracker-ai-${iso()}.md`,'text/markdown')}>Export for AI review</button><button className="primary" onClick={()=>download(JSON.stringify(days,null,2),'autonomic-daily-backup.json','application/json')}>Download JSON backup</button><label className="file">Import JSON backup<input type="file" accept="application/json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const a=JSON.parse(await f.text());await importDays(a.map(normalize));await load();alert('Backup imported')}catch{alert('Could not import')}}}/></label></section>}
</main><nav>{['Today','History','Trends','Export'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav></div>}
