import{useEffect,useMemo,useState}from'react';import{catalog,allSymptoms}from'./data';import{getAllDays,getDay,importDays,RecordDay,saveDay,Severity}from'./db';
const iso=()=>new Date().toLocaleDateString('en-CA');
const blank=(date=iso()):RecordDay=>({date,status:'Typical',burden:0,energy:0,upright:0,sleep:0,symptoms:{},mmeasurements:{weight:'',fluid:'',urine:'',urinations:'',bp:'',heartRate:'',temperature:'',weightUnit:'lb',fluidUnit:'oz',tempUnit:'°F',electrolyte:false},activity:{physical:'None',cognitive:'None',social:'None',delayed:'None'},cycle:{day:'',phase:'Unknown',pmdd:'None',note:''},notes:'',updatedAt:new Date().toISOString()});
const favoriteDefault=['Brain fog','Dizziness','Lightheadedness','Post-exertional malaise','Delayed crashes','Energy collapse','Nausea','Weakness','Non-restorative sleep','Sensory overload','Headache','Temperature dysregulation'];
function FieldScore({label,value,set}:{label:string,value:number,set:(n:number)=>void}){return <label className="score"><span>{label}</span><input aria-label={label} type="range" min="0" max="5" value={value} onChange={e=>set(+e.target.value)}/><b>{value}</b></label>}
function MiniChart({label,days,keyName,color}:{label:string;days:RecordDay[];keyName:'burden'|'energy'|null;color:string}){const vals=days.slice(-30).map(d=>keyName?d[keyName]:Number(d.measurements.weight)||0);const max=Math.max(5,...vals);const pts=vals.map((v,i)=>`${vals.length<2?0:i/(vals.length-1)*100},${40-v/max*36}`).join(' ');return <section className="card"><h3>{label}</h3>{vals.length?<svg viewBox="0 0 100 42" preserveAspectRatio="none" className="chart"><polyline fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke" points={pts}/></svg>:<p>No data yet.</p>}</section>}
export default function App(){const[tab,setTab]=useState('Today');const[date,setDate]=useState(iso());const[day,setDay]=useState<RecordDay>(blank());const[days,setDays]=useState<RecordDay[]>([]);const[saved,setSaved]=useState('');const[faves,setFaves]=useState<string[]>(()=>JSON.parse(localStorage.getItem('favorites')||JSON.stringify(favoriteDefault)));const[open,setOpen]=useState<string[]>([]);
const loadAll=async()=>setDays(await getAllDays());useEffect(()=>{getDay(date).then(v=>setDay(v||blank(date)));loadAll()},[date]);
useEffect(()=>{const t=setTimeout(()=>saveDay({...day,updatedAt:new Date().toISOString()}).then(()=>{setSaved('Saved');loadAll()}).catch(()=>setSaved('Save failed')),500);return()=>clearTimeout(t)},[day]);
const patch=(p:Partial<RecordDay>)=>setDay(d=>({...d,...p}));const sev=(name:string)=>day.symptoms[name]?.severity||0;const setSym=(name:string,severity:Severity)=>setDay(d=>({...d,symptoms:{...d.symptoms,[name]:{severity,note:d.symptoms[name]?.note||''}}}));
const toggleFav=(n:string)=>{const next=faves.includes(n)?faves.filter(x=>x!==n):faves.length<12?[...faves,n]:faves;setFaves(next);localStorage.setItem('favorites',JSON.stringify(next))};
const SymRow=({name}:{name:string})=><div className="sym" key={name}><div className="sym-title"><button className={'star '+(faves.includes(name)?'on':'')} onClick={()=>toggleFav(name)} aria-label="Pin symptom">★</button><span>{name}</span></div><div className="severity">{['None','Mild','Moderate','Severe'].map((x,i)=><button key={x} className={sev(name)===i?'selected':''} onClick={()=>setSym(name,i as Severity)}>{x}</button>)}</div>{sev(name)>0&&<input className="note" placeholder="Optional note" value={day.symptoms[name]?.note||''} onChange={e=>setDay(d=>({...d,symptoms:{...d.symptoms,[name]:{severity:sev(name),note:e.target.value}}}))}/>}</div>;
const csv=()=>{const rows:(string|number)[][]=[['Date','Status','Burden','Energy','Upright','Sleep','Fluid','Urine','Urinations','Electrolyte packet','BP','Heart rate','Temperature','Physical','Cognitive','Social/Sensory','Delayed worsening','Cycle day','Cycle phase','PMDD','Daily notes','Symptoms']];days.forEach(d=>rows.push([d.date,d.status,d.burden,d.energy,d.upright,d.sleep,d.measurements.fluid,d.measurements.urine,d.measurements.urinations,d.measurements.electrolyte?'Yes':'No',d.measurements.bp,d.measurements.heartRate,d.measurements.temperature,d.activity.physical,d.activity.cognitive,d.activity.social,d.activity.delayed,d.cycle.day,d.cycle.phase,d.cycle.pmdd,d.notes,Object.entries(d.symptoms).filter(([,v])=>v.severity>0).map(([k,v])=>`${k}:${['None','Mild','Moderate','Severe'][v.severity]}${v.note?' ('+v.note+')':''}`).join('; ') ]));download(rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n'),'autonomic-daily.csv','text/csv')};
const backup=()=>download(JSON.stringify(days,null,2),'autonomic-daily-backup.json','application/json');function download(data:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
const importFile=async(f?:File)=>{if(!f)return;const parsed=JSON.parse(await f.text());if(!Array.isArray(parsed))throw new Error('Invalid backup');await importDays(parsed);await loadAll();alert('Backup imported')};
return <div className="app"><header><div><h1>Autonomic Daily</h1><small>Private, local-first symptom log</small></div><span className="saved">{saved}</span></header><main>
{tab==='Today'&&<><section className="card date"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></section><section className="card"><h2>Quick check-in</h2><div className="status">{['Better than usual','Typical','Worse than usual','Flare / Crash'].map(x=><button className={day.status===x?'selected':''} onClick={()=>patch({status:x})}>{x}</button>)}</div><FieldScore label="Overall symptom burden" value={day.burden} set={n=>patch({burden:n})}/><FieldScore label="Available energy" value={day.energy} set={n=>patch({energy:n})}/><FieldScore label="Upright tolerance" value={day.upright} set={n=>patch({upright:n})}/><FieldScore label="Sleep quality" value={day.sleep} set={n=>patch({sleep:n})}/></section><section className="card"><h2>Pinned symptoms</h2>{faves.map(n=>SymRow({name:n}))}</section><section className="card"><h2>All symptoms</h2>{Object.entries(catalog).map(([cat,list])=><div className="category" key={cat}><button className="category-head" onClick={()=>setOpen(o=>o.includes(cat)?o.filter(x=>x!==cat):[...o,cat])}>{cat}<span>{open.includes(cat)?'−':'+'}</span></button>{open.includes(cat)&&list.map(n=>SymRow({name:n}))} name={n}/>)}</div>)}</section><section className="card"><h2>Measurements</h2><div className="grid">{([['fluid','Fluid intake'],['urine','Urine output'],['urinations','Number of urinations'],['bp','Blood pressure'],['heartRate','Heart rate'],['temperature','Temperature']] as const)
.map(([k,l])=><label>{l}<input inputMode={k==='bp'?'text':'decimal'} value={day.measurements[k]} onChange={e=>setDay(d=>({...d,measurements:{...d.measurements,[k]:e.target.value}}))}/></label>)}</div></div>

<label className="check">
  <input
    type="checkbox"
    checked={Boolean(day.measurements.electrolyte)}
    onChange={e=>setDay(d=>({
      ...d,
      measurements:{
        ...d.measurements,
        electrolyte:e.target.checked
      }
    }))}
  />
  <span>Used one electrolyte packet today</span>
</label>

<div className="grid units">
Fluid unit<select value={day.measurements.fluidUnit} onChange={e=>setDay(d=>({...d,measurements:{...d.measurements,fluidUnit:e.target.value}}))}><option>oz</option><option>mL</option></select></label><label>Temperature unit<select value={day.measurements.tempUnit} onChange={e=>setDay(d=>({...d,measurements:{...d.measurements,tempUnit:e.target.value}}))}><option>°F</option><option>°C</option></select></label></div></section><section className="card"><h2>Activity and delayed effects</h2>{(['physical','cognitive','social'] as const).map(k=><label>{k==='social'?'Social / sensory':k[0].toUpperCase()+k.slice(1)} exertion<select value={day.activity[k]} onChange={e=>setDay(d=>({...d,activity:{...d.activity,[k]:e.target.value}}))}>{['None','Light','Moderate','High'].map(x=><option>{x}</option>)}</select></label>)}<label>Delayed worsening<select value={day.activity.delayed} onChange={e=>setDay(d=>({...d,activity:{...d.activity,delayed:e.target.value}}))}>{['None','Same day','Next day','Two to three days later'].map(x=><option>{x}</option>)}</select></label></section><section className="card"><h2>Cycle pattern</h2><div className="grid"><label>Estimated cycle day<input inputMode="numeric" value={day.cycle.day} onChange={e=>setDay(d=>({...d,cycle:{...d.cycle,day:e.target.value}}))}/></label><label>Cycle phase<select value={day.cycle.phase} onChange={e=>setDay(d=>({...d,cycle:{...d.cycle,phase:e.target.value}}))}>{['Unknown','Follicular','Ovulatory','Luteal'].map(x=><option>{x}</option>)}</select></label><label>PMDD severity<select value={day.cycle.pmdd} onChange={e=>setDay(d=>({...d,cycle:{...d.cycle,pmdd:e.target.value}}))}>{['None','Mild','Moderate','Severe'].map(x=><option>{x}</option>)}</select></label></div><textarea placeholder="Cycle notes" value={day.cycle.note} onChange={e=>setDay(d=>({...d,cycle:{...d.cycle,note:e.target.value}}))}/></section><section className="card"><h2>Daily notes</h2><textarea value={day.notes} onChange={e=>patch({notes:e.target.value})}/></section></>}
{tab==='History'&&<section className="card"><h2>History</h2>{days.length?days.slice().reverse().map(d=><button className="history" onClick={()=>{setDate(d.date);setTab('Today')}}><b>{d.date}</b><span>{d.status} · burden {d.burden}/5</span></button>):<p>No records yet.</p>}</section>}
{tab==='Trends'&&<><MiniChart label="Symptom burden, last 30 entries" days={days} keyName="burden" color="#a43f55"/><MiniChart label="Energy, last 30 entries" days={days} keyName="energy" color="#2f6f68"/><section className="card"><h3>Recorded totals</h3><p>{days.length} daily records · {days.reduce((n,d)=>n+Object.values(d.symptoms).filter(x=>x.severity>0).length,0)} symptom observations</p></section></>}
{tab==='Export'&&<section className="card"><h2>Export and backup</h2><p>Your entries are stored in this browser on this device. Export backups regularly.</p><button className="primary" onClick={csv}>Download CSV</button><button className="primary" onClick={()=>window.print()}>Print / Save as PDF</button><button onClick={backup}>Download JSON backup</button><label className="file">Import JSON backup<input type="file" accept="application/json" onChange={e=>importFile(e.target.files?.[0]).catch(()=>alert('Could not import this file'))}/></label><hr/><p><b>Privacy:</b> no account, analytics, or cloud transmission is included.</p><p className="disclaimer">This report contains user-entered observations and is not a medical diagnosis.</p></section>}
</main><nav>{['Today','History','Trends','Export'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav></div>}
